before_script:
  - npm install -g bower
  - npm install -g karma
  - npm install -g karma-cli
  - bower install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
addons:
  firefox: latest
language: node_js
node_js:
  - 5.9.1







